### ISSUE TITLE
Cleanup Ember deprecations

### ISSUE THREAD

**Issue by habdelra** [cardstack/portfolio#16]
We've upgraded to Ember 3.7 in order to use the new events on the router service. As a result, I'm seeing these 2 deprecations a lot (I think they are framework deprecations):
```
DEPRECATION: You attempted to read "transition.queryParams" which is a private API. You should read the `RouteInfo` object on "transition.to" or "transition.from" which has the queryParams on it. [deprecation id: transition-state] See https://emberjs.com/deprecations/v3.x#toc_transition-state for more details.
        at logDeprecationStackTrace (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/@ember/debug/lib/deprecate.js:86:1)
        at HANDLERS.(anonymous function) (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/@ember/debug/lib/handlers.js:11:1)
        at raiseOnDeprecation (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/@ember/debug/lib/deprecate.js:110:1)
        at HANDLERS.(anonymous function) (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/@ember/debug/lib/handlers.js:11:1)
        at invoke (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/@ember/debug/lib/handlers.js:20:1)
        at deprecate (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/@ember/debug/lib/deprecate.js:146:1)
        at Transition.get (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/@ember/-internals/routing/lib/system/router.js:46:1)
        at Class.model (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/addon-tree-output/@cardstack/routing/routes/cardstack.js:15:1)
        at Class.deserialize (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/@ember/-internals/routing/lib/system/route.js:933:1)
        at UnresolvedRouteInfoByParam.getModel (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/router_js.js:726:1)
        at _rsvp.Promise.resolve.then.then.then.then (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/router_js.js:565:1)
        at tryCatcher (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/rsvp.js:313:1)
        at invokeCallback (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/rsvp.js:483:1)
        at publish (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/rsvp.js:469:1)
        at _runloop.backburner.schedule (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/ember-testing/lib/ext/rsvp.js:13:1)
        at invokeWithOnError (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/backburner.js:255:1)
        at Queue.flush (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/backburner.js:168:1)
        at DeferredActionQueues.flush (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/backburner.js:320:1)
        at Backburner._end (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/backburner.js:750:1)
        at Backburner._boundAutorunEnd (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/backburner.js:487:1)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

```
DEPRECATION: Use of `merge` has been deprecated. Please use `assign` instead. [deprecation id: ember-polyfills.deprecate-merge] See https://emberjs.com/deprecations/v3.x/#toc_ember-polyfills-deprecate-merge for more details.
        at logDeprecationStackTrace (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/@ember/debug/lib/deprecate.js:86:1)
        at HANDLERS.(anonymous function) (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/@ember/debug/lib/handlers.js:11:1)
        at raiseOnDeprecation (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/@ember/debug/lib/deprecate.js:110:1)
        at HANDLERS.(anonymous function) (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/@ember/debug/lib/handlers.js:11:1)
        at invoke (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/@ember/debug/lib/handlers.js:20:1)
        at deprecate (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/@ember/debug/lib/deprecate.js:146:1)
        at Object.merge (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/@ember/polyfills/lib/merge.js:27:1)
        at Class._cacheFastBootCookie (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/addon-tree-output/ember-cookies/services/cookies.js:133:1)
        at Class._writeFastBootCookie (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/addon-tree-output/ember-cookies/services/cookies.js:126:1)
        at Class.write (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/addon-tree-output/ember-cookies/services/cookies.js:87:1)
        at Class._write (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/addon-tree-output/ember-simple-auth/session-stores/cookie.js:236:1)
        at Class.persist (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/addon-tree-output/ember-simple-auth/session-stores/cookie.js:182:1)
        at Class.persist (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/addon-tree-output/ember-simple-auth/session-stores/adaptive.js:156:1)
        at Proxy._callStoreAsync (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/addon-tree-output/ember-simple-auth/internal-session.js:95:1)
        at Proxy._updateStore (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/addon-tree-output/ember-simple-auth/internal-session.js:165:1)
        at Proxy._clear (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/addon-tree-output/ember-simple-auth/internal-session.js:138:1)
        at Proxy._clearWithContent (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/addon-tree-output/ember-simple-auth/internal-session.js:147:1)
        at _callStoreAsync.then.restoredContent (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/addon-tree-output/ember-simple-auth/internal-session.js:86:1)
        at tryCatcher (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/rsvp.js:313:1)
        at invokeCallback (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/rsvp.js:483:1)
        at config.async (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/rsvp.js:546:1)
        at _runloop.backburner.schedule (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/ember-testing/lib/ext/rsvp.js:13:1)
        at invokeWithOnError (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/backburner.js:255:1)
        at Queue.flush (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/backburner.js:168:1)
        at DeferredActionQueues.flush (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/backburner.js:320:1)
        at Backburner._end (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/backburner.js:750:1)
        at Backburner._boundAutorunEnd (/var/folders/hz/y73qr9rn0jl_32glr10y0pkc0000gr/T/broccoli-330765t9FqUdhHz2L/out-842-broccoli_merge_trees/assets/backburner.js:487:1)
```

**Comment by habdelra** [comment]
These deprecations are now fixed in @cardstack/cardstack 0.13.51
