### ISSUE TITLE
Node version 12 is not supported

### ISSUE THREAD

**Issue by jenweber** [cardstack/portfolio#216]
If you use Node version 12 with this app, it has the following errors. Use the latest LTS version (v10) instead to avoid this error:

```
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jenweber/cardstack/portfolio/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command \"/Users/jenweber/.nvm/versions/node/v12.4.0/bin/node\" \"/Users/jenweber/cardstack/portfolio/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/jenweber/cardstack/portfolio/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/jenweber/cardstack/portfolio/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64\" \"--napi_version=4\" \"--node_abi_napi=napi\"
gyp ERR! cwd /Users/jenweber/cardstack/portfolio/node_modules/fsevents
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/jenweber/.nvm/versions/node/v12.4.0/bin/node /Users/jenweber/cardstack/portfolio/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/jenweber/cardstack/portfolio/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/jenweber/cardstack/portfolio/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi'
```

**Comment by jenweber** [comment]
We should add this to our README and figure out why this doesn't work for node 12, eventually.
